server:
  servlet:
    context-path: /api

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./resistanceNetworkDb;MODE=MYSQL;AUTO_SERVER=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS RESISTANCE_NETWORK
    username: user
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: RESISTANCE_NETWORK
        format_sql: true
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2-console
